export const LOCAL_STORAGE_KEYS = {
  SELECTED_LANGUAGE: 'SELECTED_LANGUAGE',
}

export const SESSION_STORAGE_KEYS = {
  REFERRAL_CODE: 'REFERRAL_CODE',
  ADDRESS_DETAIL: 'ADDRESS_DETAIL',
  FRIEND_INVITATION_UID: 'FRIEND_INVITATION_UID',
  WEB_CLIENT_NANOID: 'WEB_CLIENT_NANOID'
}
